### ISSUE TITLE
Acceleration fix doesn't work

### ISSUE THREAD

**Issue by Keith94** [AWilliams17/Halo-CE-Mouse-Tool#1]
Similar to the previous mouse fix, the sensitivity can be patched, but acceleration is still present. I'm running Halo Custom Edition 1.10 on Windows 8. Any ideas?

**Comment by AWilliams17** [comment]
Darn, that's what I was afraid of.
I'll try messing around with the patching code later on tonight and see if I can dig something out.

**Comment by AWilliams17** [comment]
I think I just fixed it completely. I found the REAL addresses. Do you have a Skype or a Steam I can talk to you on? I'd like to run this by someone.

**Comment by Keith94** [comment]
Discord? https://discord.gg/BaWTKJC
