### ISSUE TITLE
Sensitivity Values are unreadable on Dark themes for Windows

### ISSUE THREAD

**Issue by BinToss** [AWilliams17/Halo-CE-Mouse-Tool#3]
![image](https://user-images.githubusercontent.com/7243190/59479825-2d79f180-8e13-11e9-8dc7-33298aec313c.png)

**Comment by 77Mynameislol77** [comment]
looks fine to me 

![image](https://user-images.githubusercontent.com/35608876/59920441-cff52e80-942a-11e9-8925-7d611a67b830.png)

**Comment by BinToss** [comment]
Interesting. Which dark theme are you using?

**Comment by 77Mynameislol77** [comment]
the one included with windows build 18362

**Comment by BinToss** [comment]
That still applies the classic light theme to conventional applications. Windows 10 Dark Mode only applies to UWP apps and Windows File Explorer.

I'm using the Penumbra 10 custom theme. https://www.deviantart.com/scope10/art/Penumbra-10-Windows-10-visual-style-568740374

**Comment by AWilliams17** [comment]
Sorry for getting to you so late, I have no idea why Github didn't show me a notification for this.

I'm afraid I really can't help though - UltraUX from my experience is extremely buggy and broken and the recent version I have seen uses a ridiculous method of 'patching' the system files to allow for custom themes (and by patch, I mean it actually just replaces the newer versions of the file with the version from an older Windows installation which has been patched. lol.)

I'll leave it open though for a while in the hopes that someone else can help you. I really have no idea how to go about diagnosing this problem, and I'm pretty sure it goes well beyond what I can reasonably fix.

**Comment by BinToss** [comment]
Now that I actually put some thought into it, this is more of a UltraUXThemePatcher issue.

**Comment by AWilliams17** [comment]
Roger that, closing issue.
I'll leave the conversation unlocked though just incase someone else happens along and can give some insight on how I can go about making it compatible with UltraUX. I'm not even sure if that's possible.

**Comment by BinToss** [comment]
I'd like to add that the problem appears to be UXThemePatcher detects the input box background as text instead of a background. This could be because...
...it isn't handling that type of input box correctly under the hood
...or it's themeing rules detects existing darks as having to be inverted unless specified otherwise
...or it could be the way the HCEMT applies it's own theme to the input box which UXThemePatcher doesn't account for
...or it could just be the Penumbra custom theme and my lack of thoroughly testing the issue.
