### ISSUE TITLE
Inclusion in the SPV3 Loader

### ISSUE THREAD

**Issue by MirisWisdom** [AWilliams17/Halo-CE-Mouse-Tool#4]
I'm up for including your HCE Mouse Tool in the SPV3 loader, but the licence incompatibilities are a roadblock:

- the [SPV3 loader](https://source.n2.network/spv3/tree/) is licensed under the permissive Zlib licence; and
- the mouse tool is licenced under the viral GPLV3 licence.

Would you be keen to declare an exempt for SPV3?

**Comment by AWilliams17** [comment]
Honestly just chose the license as an afterthought.
I'm down for changing the license if need be, I don't really care.

What's the standard way of going about declaring something exempt like you're asking, though?

**Comment by MirisWisdom** [comment]
Gave it a thought. If you want, you could duo-licence your project under both GPL and a permissive licence of your choice. Just commit an additional licence file and you're good to go.

Mind you, this allows anyone to fork your project to a close sourced one.
